"""SecretRedactor — intercepts MCP tool results and strips secret values.

This module sits between the MCP client and the Agent Core's LLM conversation.
Every tool result passes through the redactor BEFORE being added to the LLM
message history. The redactor:

1. **Redacts tool results**: Removes secret values from MCP responses,
   keeping only metadata and key names for the LLM to reason about.
   The full unredacted response is stored in the SecretContext for the
   API consumer.

2. **Restores placeholders**: When the LLM produces tool-call arguments
   containing placeholder tokens (from the PromptSanitizer), the redactor
   replaces them with real secret values before the call reaches the MCP server.

Security contract:
    - ``redact_tool_result()`` is called BEFORE every tool result enters the LLM.
    - ``restore_placeholders()`` is called BEFORE every tool call reaches MCP.
    - The redactor uses policies from ``policies.py`` for tool-specific rules.
    - Unknown tools use conservative redaction (all values stripped).

Usage in the Agent Core reasoning loop::

    # After MCP tool call returns:
    redacted_result = redactor.redact_tool_result(tool_name, raw_result, context)
    messages.append({"role": "tool", "content": redacted_result})

    # Before MCP tool call:
    real_arguments = redactor.restore_placeholders(arguments, context)
    mcp_result = await mcp_client.call_tool(tool_name, real_arguments)
"""

from __future__ import annotations

import json
import re
from typing import Any

from src.agent.redaction.context import SecretContext
from src.agent.redaction.policies import get_policy_for_tool
from src.logging import get_logger

logger = get_logger(__name__)

# Pattern to detect placeholder tokens in strings
_PLACEHOLDER_PATTERN = re.compile(r"\[SECRET_VALUE_\d+\]")


class SecretRedactor:
    """Redacts secret values from MCP tool results and restores placeholders in tool arguments.

    This class is stateless — all secret state lives in the ``SecretContext``
    passed to each method. A single ``SecretRedactor`` instance can be shared
    across requests.

    The redactor delegates to per-tool-type ``RedactionPolicy`` instances
    for the actual redaction logic. See ``policies.py``.
    """

    def redact_tool_result(
        self,
        tool_name: str,
        result: Any,
        context: SecretContext,
    ) -> str:
        """Redact secret values from an MCP tool result before it enters the LLM conversation.

        The full unredacted result is stored in ``context`` for inclusion in
        the API consumer's response.

        Parameters
        ----------
        tool_name:
            The MCP tool that produced this result (e.g. ``"vault_kv_read"``).
        result:
            The raw tool result from the MCP server. May be a string (JSON),
            dict, or other type.
        context:
            The request-scoped ``SecretContext`` for storing unredacted data.

        Returns
        -------
        str
            A JSON string of the redacted result, safe to include in the LLM
            conversation as a tool result message.
        """
        policy = get_policy_for_tool(tool_name)
        policy_name = type(policy).__name__

        try:
            redaction_result = policy.redact(tool_name, result)
            redacted = redaction_result["redacted"]
        except Exception:
            # If redaction fails, use ultra-conservative fallback:
            # redact EVERYTHING.
            logger.exception(
                "redaction.policy_error",
                tool_name=tool_name,
                policy=policy_name,
            )
            redacted = {
                "error": "Redaction processing failed. Tool result fully redacted for safety.",
                "tool_name": tool_name,
            }

        logger.info(
            "redaction.tool_result_redacted",
            tool_name=tool_name,
            policy=policy_name,
            # NEVER log the result content
        )

        # Return as JSON string for inclusion in LLM messages
        if isinstance(redacted, str):
            return redacted
        return json.dumps(redacted, indent=2, default=str)

    def restore_placeholders(
        self,
        arguments: dict[str, Any],
        context: SecretContext,
    ) -> dict[str, Any]:
        """Replace placeholder tokens in tool-call arguments with real secret values.

        Called BEFORE a tool call is forwarded to the MCP server. The LLM may
        have included placeholder tokens like ``[SECRET_VALUE_1]`` in its
        generated arguments (because the PromptSanitizer replaced real values
        in the prompt). This method restores the real values so the MCP server
        receives correct data.

        Parameters
        ----------
        arguments:
            The tool-call arguments generated by the LLM, potentially containing
            placeholder tokens.
        context:
            The request-scoped ``SecretContext`` with placeholder → value mappings.

        Returns
        -------
        dict[str, Any]
            A new dict with all placeholder tokens replaced by their real values.
            The original dict is not modified.
        """
        if not context.has_placeholders():
            return arguments

        restored = self._deep_restore(arguments, context)

        # Log that we performed restoration (without logging the values)
        placeholder_count = self._count_placeholders_in(arguments)
        if placeholder_count > 0:
            logger.info(
                "redaction.placeholders_restored",
                placeholder_count=placeholder_count,
                # NEVER log the actual values
            )

        return restored

    def redact_error_message(
        self,
        error_message: str,
        context: SecretContext,
    ) -> str:
        """Redact any secret values that may appear in error messages.

        Vault or MCP server error messages might accidentally include secret
        values (e.g. "cannot write value 's3cret' to path ..."). This method
        replaces any known secret values (from the placeholder mapping) with
        ``[REDACTED]``.

        Parameters
        ----------
        error_message:
            The raw error message from the MCP server or Vault.
        context:
            The request-scoped ``SecretContext`` with known secret values.

        Returns
        -------
        str
            The error message with any known secret values replaced.
        """
        if not context.has_placeholders():
            return error_message

        # Use resolve_all_placeholders in reverse: replace real values with [REDACTED]
        # by iterating the known placeholder-to-value mappings.
        redacted = error_message
        # Access the internal mapping via resolve to check each known value
        # We iterate through placeholder indices (1-based) up to the counter
        for i in range(1, context.placeholder_count + 1):
            placeholder = f"[SECRET_VALUE_{i}]"
            real_value = context.resolve_placeholder(placeholder)
            if real_value and len(real_value) >= 4 and real_value in redacted:
                redacted = redacted.replace(real_value, "[REDACTED]")

        return redacted

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _deep_restore(self, data: Any, context: SecretContext) -> Any:
        """Recursively replace placeholder tokens with real values in a data structure."""
        if isinstance(data, dict):
            return {k: self._deep_restore(v, context) for k, v in data.items()}
        elif isinstance(data, list):
            return [self._deep_restore(item, context) for item in data]
        elif isinstance(data, str):
            if _PLACEHOLDER_PATTERN.search(data):
                return context.resolve_all_placeholders(data)
            return data
        else:
            return data

    def _count_placeholders_in(self, data: Any) -> int:
        """Count placeholder tokens in a data structure."""
        count = 0
        if isinstance(data, dict):
            for v in data.values():
                count += self._count_placeholders_in(v)
        elif isinstance(data, list):
            for item in data:
                count += self._count_placeholders_in(item)
        elif isinstance(data, str):
            count += len(_PLACEHOLDER_PATTERN.findall(data))
        return count
